# Generated by Django 5.0.7 on 2026-04-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('sign', 'Знак'), ('cusp', 'Куспид')], max_length=16)),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=16)),
                ('source_file', models.CharField(max_length=255)),
                ('characteristic_markdown', models.TextField()),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=160)),
                ('interaction_type', models.TextField(blank=True)),
                ('bound_state', models.TextField(blank=True)),
                ('why', models.TextField(blank=True)),
                ('quantum_dynamics', models.TextField(blank=True)),
                ('intimacy', models.TextField(blank=True)),
                ('synthesis', models.TextField(blank=True)),
                ('vulnerabilities', models.TextField(blank=True)),
                ('result_line', models.TextField(blank=True)),
                ('enriched_text', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='core.profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='core.profile')),
            ],
            options={
                'ordering': ('source__code', 'target__code'),
                'unique_together': {('source', 'target')},
            },
        ),
    ]
